#!/usr/bin/env bash
#multiplos de 3y 5
i="1"
while [ $i -lt 101 ]
do
echo $i
case $i in
    i%3 == 0*)
	echo "Fizz";;
    #{((i%5 == 0))})
#	echo "Buzz";;
 #   { ((i%15 == 0)) })
#	echo "FizzBuzz";;

esac
i=$((i+1))
done
