#!/usr/bin/env bash
#multiplos de 3y 5
i="1"
while [ $i -lt 101 ]
do
    if (( $i%3 == 0 ))
    then
	echo "fizz"
    elif (( $i%5 == 0 ))
    then
	echo "Buzz"
    elif (( $i%15 == 0 ))
    then
	echo "FizzBuzz"
    else
	echo $i
fi
i=$((i+1))
done
