#!/usr/bin/env bash
#utiliza 7 campos almacenados de 1-7
i="/etc/passwd"
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do 
 echo "The user $f1 is part of the $f2 gang, lives in $f3 and rides $f4. $f5's place is protected by the passcode $f6, more info about the user here: $f7"
done < $i
