#!/usr/bin/env bash
#Script that loops from 1 to 10 displays bad luck good luck and Best School
i="0"
while [ $i -lt 10 ]
do
    if ((i == 3))
    then
	echo "bad luck"
    elif ((i == 7))
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    i=$((i+1))
done
	    
