#!/usr/bin/env bash
#while case Bash script that displays numbers from 1 to 20 and
i="0";
while [ $i -lt 7 ]
do
echo $i
case $i in
"3") echo "bad luck from China";; 
"8") echo "bad luck from Japan";;
"16") echo "bad luck from Italy";;

esac
i=$((i+1))
done
