#!/usr/bin/env bash
#muestra la hora y seguido los 50 minutos
h="0"
m="1"
while [ $h -lt 12 ]
do
    echo Hour:$h
    while [ $m -lt 60 ]
    do 
    echo $m
    m=$((m+1))
    done
    h=$((h+1))
    m="1"
done
